I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    define PKFlag = false
  File "game/script.rpy", line 10, in <module>
    define PKFlag = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script
    define PKFlag = false
  File "C:\Users\Jake\Documents\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 2235, in execute
    self.set()
  File "C:\Users\Jake\Documents\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 2249, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Jake\Documents\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 10, in <module>
    define PKFlag = false
NameError: name 'false' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Halls of the Unseen 1.0
Thu Nov 21 10:09:25 2024
