I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 570, in script
    if bag_flag:
  File "game/script.rpy", line 570, in <module>
    if bag_flag:
NameError: name 'bag_flag' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 570, in script
    if bag_flag:
  File "C:\Users\Jake\Documents\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Jake\Documents\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Jake\Documents\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 570, in <module>
    if bag_flag:
NameError: name 'bag_flag' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Halls of the Unseen 1.0
Thu Dec 12 03:17:49 2024
